### ISSUE TITLE
style nav bar

### ISSUE THREAD

**Issue by nothingnessbird** [sedillon93/portfolio#7]
https://github.com/sedillon93/portfolio/blob/9634c2ef4f2713a3b53f2d275c8f1ec8c24d62f9/css/layout.css#L47

currently the nav bar text is too large to red when the page is at desktop size, maybe style the nav bar so that the text is smaller or the bar is larger when the screen is large

**Comment by sedillon93** [comment]
Fixed it; had font-size for desktop size & mobile size displays switched...
